maintainer       "John Doe"
maintainer_email "johndoe@example.com"
depends          "apache2"
depends          "php"
recipe           "web", "Installs and configures a web server."
supports         "centos"
