maintainer       "John Doe"
maintainer_email "johndoe@example.com"
depends          "apache2"
depends          "php"
depends          "git"
recipe           "all", "Installs things needed on all our servers."
recipe           "web", "Installs and configures a web server."
supports         "centos"
